=== JulianHurst/ProjetXML/ProjetXML-master/Cuisine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Cuisines">
		<xs:annotation>
			<xs:documentation>Le site de recettes de cuisine</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ListeRecette"/>
				<xs:element ref="ListeAuteur"/>
				<xs:element ref="Categories"/>
				<xs:element ref="ListeIngredient"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ListeRecette">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Recette" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Recette">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Titre"/>			
				<xs:element ref="Resume"/>
				<xs:element ref="Photo"/>
				<xs:element ref="Date"/>
				<xs:element ref="Difficulte"/>
				<xs:element ref="ListeIngredients"/>
				<xs:element ref="NbPersonnes"/>
				<xs:element ref="TpsPreparation"/>
				<xs:element ref="TpsCuisson"/>
				<xs:element ref="TpsRepos"/>
				<xs:element ref="Desc"/>
				<xs:element ref="Note" minOccurs="0"/>				
			</xs:sequence>
			<xs:attribute name="ID" type="xs:string"/>							
		</xs:complexType>
	</xs:element>
	<xs:element name="Titre">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="2"/>
				<xs:maxLength value="40"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>			
	<xs:element name="Resume">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>	
	<xs:element name="Photo">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>	
	</xs:element>	
	<xs:element name="Date">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>	
	<xs:element name="Difficulte">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>	
	<xs:element name="ListeIngredients">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Ingredients" minOccurs="2" maxOccurs="20"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Ingredients">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Quantite"/>
				<xs:element ref="Unite" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Quantite">
		<xs:simpleType>
			<xs:restriction base="xs:integer"/>
		</xs:simpleType>
	</xs:element>	
	<xs:element name="Unite">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>	
	<xs:element name="NbPersonnes">
		<xs:simpleType>
			<xs:restriction base="xs:integer"/>
		</xs:simpleType>
	</xs:element>	
	<xs:element name="TpsPreparation">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>	
	<xs:element name="TpsCuisson">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>	
	<xs:element name="TpsRepos">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>	
	<xs:element name="Desc">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>	
	<xs:element name="Note">
		<xs:simpleType>
			<xs:restriction base="xs:decimal"/>
		</xs:simpleType>
	</xs:element>	
	<xs:element name="ListeAuteur">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Auteur" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Auteur">
		<xs:complexType>				
			<xs:sequence>
				<xs:element ref="Nom"/>
				<xs:element ref="Age"/>
				<xs:element ref="Pays"/>
				<xs:element ref="Sexe"/>
				<xs:element ref="Bio"/>
				<xs:element ref="ref-recette"/>
				<xs:any minOccurs="0"/>								
			</xs:sequence>						
			<xs:attribute name="IDAuteur" type="xs:string"/>													
		</xs:complexType>
	</xs:element>
	<xs:element name="Nom" type="xs:string"/>	
	<xs:element name="Age" type="xs:integer"/>	
	<xs:element name="Pays" type="xs:string"/>	
	<xs:element name="Sexe" type="xs:string"/>	
	<xs:element name="Bio" type="xs:string"/>	
	<xs:element name="ref-recette">
		<xs:complexType>
			<xs:attribute name="ref" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Categories">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Category" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="desc" use="optional" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Category">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SousCategory" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="nom" use="required" type="xs:string"/>
			<xs:attribute name="desc" use="optional" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SousCategory">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Recettes" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="nom" use="required" type="xs:string"/>
			<xs:attribute name="desc" use="optional" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Recettes">
		<xs:complexType>
			<xs:attribute name="ref" use="required" type="xs:string"/>			
		</xs:complexType>
	</xs:element>
	<xs:element name="ListeIngredient">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Ingredient"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Ingredient">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Nom"/>
				<xs:element ref="ApportNut" minOccurs="0"/>
				<xs:element ref="ApportEn" minOccurs="0"/>
				<xs:element ref="Saison" minOccurs="0"/>
				<xs:element ref="Descriptif" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="IDIngredient" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ApportNut" type="xs:string"/>	
	<xs:element name="ApportEn" type="xs:string"/>	
	<xs:element name="Saison" type="xs:string"/>	
	<xs:element name="Descriptif" type="xs:string"/>	
</xs:schema>

=== JulianHurst/ProjetXML/ProjetXML-master/Cuisine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Cuisines SYSTEM "Cuisine.dtd">
<?xml-stylesheet type="text/xsl" href="file:///C:/Users/h12026079/Desktop/ProjetXML-master/Cuisine.xsl"?>
<Cuisines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/h12026079/Desktop/Cuisine.xsd">
	<ListeRecette>
		<Recette ID="A">
			<Titre>Verrine au muesli, pommes et fromage blanc</Titre>
			<Resume>Une verrine</Resume>
			<Photo>http://www.odelices.com/images/recettes/verrine_muesli_fromage_blanc_pommes_spiruline-360x380.jpg</Photo>
			<Date>21-01-2016</Date>
			<Difficulte>Façile</Difficulte>
			<ListeIngredients>
				<Ingredients>
					<Quantite>80</Quantite>
					<Unite>g</Unite>
				</Ingredients>
				<Ingredients>
					<Quantite>400</Quantite>
					<Unite>g</Unite>
				</Ingredients>
				<Ingredients>
					<Quantite>40</Quantite>
					<Unite>g</Unite>
				</Ingredients>
				<Ingredients>
					<Quantite>1</Quantite>
					<Unite>cuillerée</Unite>
				</Ingredients>
				<Ingredients>
					<Quantite>2</Quantite>
				</Ingredients>
				<Ingredients>
					<Quantite>1</Quantite>
					<Unite>poignée</Unite>
				</Ingredients>
			</ListeIngredients>
			<NbPersonnes>4</NbPersonnes>
			<TpsPreparation>10 min</TpsPreparation>
			<TpsCuisson>-</TpsCuisson>
			<TpsRepos>-</TpsRepos>
			<Desc>Une verrine</Desc>
		</Recette>
		<Recette ID="B">
			<Titre>Pâtes au beurre</Titre>
			<Resume/>
			<Photo/>
			<Date/>
			<Difficulte/>
			<ListeIngredients>
				<Ingredients>
					<Quantite>20</Quantite>
				</Ingredients>
				<Ingredients>
					<Quantite>25</Quantite>
				</Ingredients>
			</ListeIngredients>
			<NbPersonnes>4</NbPersonnes>
			<TpsPreparation/>
			<TpsCuisson/>
			<TpsRepos/>
			<Desc/>
		</Recette>
		<Recette ID="C">
			<Titre>Oeuf sur le plat</Titre>
			<Resume/>
			<Photo/>
			<Date/>
			<Difficulte/>
			<ListeIngredients>
				<Ingredients>
					<Quantite>20</Quantite>
				</Ingredients>
				<Ingredients>
					<Quantite>25</Quantite>
				</Ingredients>
			</ListeIngredients>
			<NbPersonnes>5</NbPersonnes>
			<TpsPreparation/>
			<TpsCuisson/>
			<TpsRepos/>
			<Desc/>
		</Recette>
		<Recette ID="D">
			<Titre>Frites</Titre>
			<Resume/>
			<Photo/>
			<Date/>
			<Difficulte/>
			<ListeIngredients>
				<Ingredients>
					<Quantite>8</Quantite>
				</Ingredients>
				<Ingredients>
					<Quantite>10</Quantite>
				</Ingredients>
			</ListeIngredients>
			<NbPersonnes>2</NbPersonnes>
			<TpsPreparation/>
			<TpsCuisson/>
			<TpsRepos/>
			<Desc/>
		</Recette>
		<Recette ID="E">
			<Titre>Salade verte</Titre>
			<Resume/>
			<Photo/>
			<Date/>
			<Difficulte/>
			<ListeIngredients>
				<Ingredients>
					<Quantite>40</Quantite>
				</Ingredients>
				<Ingredients>
					<Quantite>65</Quantite>
				</Ingredients>
			</ListeIngredients>
			<NbPersonnes>9</NbPersonnes>
			<TpsPreparation/>
			<TpsCuisson/>
			<TpsRepos/>
			<Desc/>
		</Recette>
		<Recette ID="F">
			<Titre>Gratin de courgettes</Titre>
			<Resume/>
			<Photo/>
			<Date/>
			<Difficulte/>
			<ListeIngredients>
				<Ingredients>
					<Quantite>100</Quantite>
				</Ingredients>
				<Ingredients>
					<Quantite>23</Quantite>
				</Ingredients>
			</ListeIngredients>
			<NbPersonnes>3</NbPersonnes>
			<TpsPreparation/>
			<TpsCuisson/>
			<TpsRepos/>
			<Desc/>
		</Recette>
		<Recette ID="G">
			<Titre>Oeuf à cheval avec sa ribembelle d'herbe</Titre>
			<Resume/>
			<Photo/>
			<Date/>
			<Difficulte/>
			<ListeIngredients>
				<Ingredients>
					<Quantite>55</Quantite>
				</Ingredients>
				<Ingredients>
					<Quantite>22</Quantite>
				</Ingredients>
			</ListeIngredients>
			<NbPersonnes>6</NbPersonnes>
			<TpsPreparation/>
			<TpsCuisson/>
			<TpsRepos/>
			<Desc/>
		</Recette>
		<Recette ID="H">
			<Titre>Pomme au four</Titre>
			<Resume/>
			<Photo/>
			<Date/>
			<Difficulte/>
			<ListeIngredients>
				<Ingredients>
					<Quantite>80</Quantite>
				</Ingredients>
				<Ingredients>
					<Quantite>15</Quantite>
				</Ingredients>
			</ListeIngredients>
			<NbPersonnes>3</NbPersonnes>
			<TpsPreparation/>
			<TpsCuisson/>
			<TpsRepos/>
			<Desc/>
		</Recette>
	</ListeRecette>
	<ListeAuteur>
		<Auteur IDAuteur="Kevin">
			<Nom>Gare à Bedian</Nom>
			<Age>25</Age>
			<Pays>France</Pays>
			<Sexe>Hermaphrodite</Sexe>
			<Bio>Biodégradable</Bio>
			<ref-recette ref="A"/>
		</Auteur>
		<Auteur IDAuteur="Julian">
			<Nom>Hurst</Nom>
			<Age>21</Age>
			<Pays>France</Pays>
			<Sexe>M</Sexe>
			<Bio>blablablablablablablablablablbalablablablablablablabla</Bio>
			<ref-recette ref="B"/>
		</Auteur>
		<Auteur IDAuteur="Machin">
			<Nom>Hurst</Nom>
			<Age>21</Age>
			<Pays>France</Pays>
			<Sexe>M</Sexe>
			<Bio>blablablablablablablablablablbalablablablablablablabla</Bio>
			<ref-recette ref="C"/>
		</Auteur>
		<Auteur IDAuteur="Truc">
			<Nom>Hurst</Nom>
			<Age>21</Age>
			<Pays>France</Pays>
			<Sexe>M</Sexe>
			<Bio>blablablablablablablablablablbalablablablablablablabla</Bio>
			<ref-recette ref="D"/>
		</Auteur>
		<Auteur IDAuteur="Dante">
			<Nom>Alig</Nom>
			<Age>666</Age>
			<Pays>Italie</Pays>
			<Sexe>Chaise</Sexe>
			<Bio>Ecrivain</Bio>
			<ref-recette ref="E"/>
		</Auteur>
		<Auteur IDAuteur="Pomme_Smith">
			<Nom>Granny</Nom>
			<Age>50</Age>
			<Pays>Djibouti</Pays>
			<Sexe>Fruit</Sexe>
			<Bio/>
			<ref-recette ref="F"/>
		</Auteur>
		<Auteur IDAuteur="Lodo">
			<Nom>Uretra</Nom>
			<Age>98</Age>
			<Pays>Corse</Pays>
			<Sexe>F</Sexe>
			<Bio>Spécialiste Prolog</Bio>
			<ref-recette ref="G"/>
		</Auteur>
		<Auteur IDAuteur="Luigi">
			<Nom>Santocanale</Nom>
			<Age>43</Age>
			<Pays>Italie</Pays>
			<Sexe>Haskell</Sexe>
			<Bio>Professeur</Bio>
			<ref-recette ref="H"/>
		</Auteur>
	</ListeAuteur>
	<Categories desc="Categories de plats">
		<Category nom="Entrée" desc="">
			<SousCategory nom="Entrées Chaudes" desc="">
				<Recettes ref="A"/>
			</SousCategory>
			<SousCategory nom="Entrées Froides" desc="">
				<Recettes ref="B"/>
			</SousCategory>
		</Category>
		<Category nom="Plat" desc="">
			<SousCategory nom="Viande" desc="">
				<Recettes ref="C"/>
			</SousCategory>
			<SousCategory nom="Poisson" desc="">
				<Recettes ref="D"/>
			</SousCategory>
		</Category>
	</Categories>
	<ListeIngredient>
		<Ingredient IDIngredient="Pomme">
			<Nom>Pomme</Nom>
		</Ingredient>
	</ListeIngredient>
</Cuisines>
